---
- name: Set up dotfiles
  hosts: localhost
  tasks:
  - name: Copy all dotfiles
    copy: 
      src: "{{ item }}"
      dest: "{{ lookup('env','HOME') + '/' }}"
      mode: '0644'
    with_items:
      - "{{ playbook_dir + '/files/' }}"